/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Matematica */

#ifndef _Included_Matematica
#define _Included_Matematica
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Matematica
 * Method:    somar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Matematica_somar(JNIEnv *ambiente_java, jobject este_objeto, jint parcela1, jint parcela2);

#ifdef __cplusplus
}
#endif
#endif
