/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClassePrincipal */

#ifndef _Included_ClassePrincipal
#define _Included_ClassePrincipal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ClassePrincipal
 * Method:    cumprimentos
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ClassePrincipal_cumprimentos(JNIEnv *ambiente_java, jobject parametro_objeto1);

#ifdef __cplusplus
}
#endif
#endif
