/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinhaClasse */

#ifndef _Included_MinhaClasse
#define _Included_MinhaClasse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinhaClasse
 * Method:    funcao1_cpp
 * Signature: ()V
 */

//JNIEXPORT void JNICALL Java_MinhaClasse_funcao1_1cpp(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_MinhaClasse_funcao1_1cpp(JNIEnv *ambiente_java, jobject este_objeto);

#ifdef __cplusplus
}
#endif
#endif
